#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use \App\Commands\CountVocationDays;

require __DIR__ . '/vendor/autoload.php';

$app = new Application();

$command = new CountVocationDays();

$app->add($command);

$app->run();